### PR TITLE
Feat/notifications

### PR DESCRIPTION
**Pull request by BenjaminBrehier**
Notification system Read/Write

### CODE REVIEW

**Review by Finalblue — DISMISSED** [review]
Good

**Review by Finalblue — DISMISSED** [review]
Approved

**Review by Finalblue — APPROVED** [review]
Re - approved, after a merge

**Review by Finalblue — DISMISSED** [review]

**Review by benji78 — DISMISSED** [review]
:+1:

**Review by benji78 — APPROVED** [review]

**Review by benji78 — DISMISSED** [review]

**Pull request merged**
